version: "3.8"
services:
  tt_scanner_buddy:
    image: your-dockerhub-user/tt_scanner_buddy:latest
    container_name: tt_scanner_buddy
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
